---
- name: add several users
  hosts: all
  tasks:
   user:
    name: "{{item.name}}"
    state: present
    groups: "{{item.groups}}"
   with_items:
    - { name: 'testuser1', groups: 'wheel' }
    - { name: 'testuser2', groups: 'root' }
...
