---
- name: Install apache on Nodes
  hosts: all
  tasks:
   - name: Install apache on all nodes
     apt:
       name: apache2
       state: present
       update_cache: yes
   - name: TO change the default page of apache
     copy:
      content: "Hello World. This is Tirupathi Reddy"
      dest: /var/www/html/index.html
   - name: To restart the apache servers
     service:
      name: apache2
      state: restarted   
...
