---
- name: setup docker on all the managed nodes
  hosts: all
  tasks:
   - name: install python pip
     apt:
      name: python3-pip
      state: present
   - name: install docker on all the nodes
     shell: "{{item}}"
     with_items:
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - pip3 install docker.py
...
