---
- name: create 2 ngnix container on all nodes
  hosts: all
  tasks:
   - name: start nginx containers
     docker_container:
      image: nginx
      name: "myapp{{item}}"
     with_sequence: count=2  
...
