---
- name: create a file & create the directory if the file exists
  hosts: all
  tasks:
   - name: create a file
     file:
      name: /home/ubuntu/file_reddy
      state: touch
   - name: Check if the created file exists or not
     stat:
      path: /home/ubuntu/file_nani
     register: b
   - name: create the directory of the above file exists
     file:
      name: dir_abc
      state: directory
     when:
      b.stat.exists== true       
...
