---
- name: Install tomcat and copy file 
  hosts: all
  tasks:
   - block:
      - name: install tomcat 7
        apt:
         name: tomcat7
         state: present
         update_cache: yes
     rescue:
      - name: install tomcat8
        apt:
         name: tomcat
         state: present
         update_cache: yes
     always:
      - name: copy file from controller to all nodes
        copy:
         src: /home/ubuntu/playbooks/playbook3.yml
         dest: /home/ubuntu/playbook1.yml       
...
